name: hr_management
description: HR Management System - Absensi, Penggajian, dan Cuti Karyawan
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  fl_chart: ^0.66.0
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^13.0.0
  
  # Data & Storage
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  
  # Supabase
  supabase_flutter: ^2.3.4

  # Utils
  uuid: ^4.3.3
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

